config/routes.rb
Research4::Application.routes.draw do
  resources :favorites

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :submissions
    match '/submissions/new/:jobid', :to => 'submissions#new', :as => "submission_new"
  resources :jobs
  resources :users
    match '/profile/:id', :to => 'users#profile', :as => "user_profile"
    match '/users/:id/changepassword', :to => 'users#changepassword', :as => "changepassword_user"
  resources :sessions, :only => [:new, :create, :destroy]
    match '/signup/student',  :to => 'users#new0', :as => 'signup0'
    match '/signup/professor', :to => 'users#new1', :as => 'signup1'
    match '/signin/student',  :to => 'sessions#new0', :as => 'signin0'
    match '/signin/faculty',  :to => 'sessions#new1', :as => 'signin1'
    match '/signout', :to => 'sessions#destroy', :as => 'signout'
    match '/session/retry/:usertype', :to => 'sessions#create'
    match '/help', :to => 'sessions#new'
    match '/welcome/:id/:code', :to => 'users#welcome'
  root :to => 'sessions#new'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
belongs_to :user
belongs_to :job

attr_accessible :favorite, :job_id, :user_id

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully created.') }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br />
    <%= f.text_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :favorite %><br />
    <%= f.text_field :favorite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>User</th>
    <th>Job</th>
    <th>Favorite</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.user_id %></td>
    <td><%= favorite.job_id %></td>
    <td><%= favorite.favorite %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @favorite.user_id %>
</p>

<p>
  <b>Job:</b>
  <%= @favorite.job_id %>
</p>

<p>
  <b>Favorite:</b>
  <%= @favorite.favorite %>
</p>


<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>