config/routes.rb
Research4::Application.routes.draw do
  resources :favorites

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :submissions
    match '/submissions/new/:jobid', :to => 'submissions#new', :as => "submission_new"
  resources :jobs
  resources :users
    match '/profile/:id', :to => 'users#profile', :as => "user_profile"
    match '/users/:id/changepassword', :to => 'users#changepassword', :as => "changepassword_user"
  resources :sessions, :only => [:new, :create, :destroy]
    match '/signup/student',  :to => 'users#new0', :as => 'signup0'
    match '/signup/professor', :to => 'users#new1', :as => 'signup1'
    match '/signin/student',  :to => 'sessions#new0', :as => 'signin0'
    match '/signin/faculty',  :to => 'sessions#new1', :as => 'signin1'
    match '/signout', :to => 'sessions#destroy', :as => 'signout'
    match '/session/retry/:usertype', :to => 'sessions#create'
    match '/help', :to => 'sessions#new'
    match '/welcome/:id/:code', :to => 'users#welcome'
  root :to => 'sessions#new'

end

app/models/job.rb
class Job < ActiveRecord::Base
  # Jobs have many applications but belong to a "user" (professor)
  has_many :submissions
  has_many :favorites
  belongs_to :user
  
  #named_scope :with_department, lambda {|department| { :conditions => {User.find(:user_id).department => department} } }

  # validations for inputs
  attr_accessible :title, :funding, :position, :location, :duration, :description, :user_id
  
  # search method for description
  def self.searchdescription(search)
    if search
      where('description LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
     validates :funding, :length => { :maximum => 200 }
     validates_length_of :position, :maximum => 50
     validates :location, :length => { :maximum => 50 }
     validates :duration, :length => { :maximum => 50 }
     validates :description, :presence => true
     validates_length_of :description, :allow_blank => true, :maximum => 5000
     validates_length_of :title, :allow_blank => true, :maximum => 50
     validates :title, :presence => true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  #make sure user is logged in
  before_filter :authenticate

  helper_method :sort_column, :sort_direction
  
  # lists all jobs
  def index  
    @title = 'Jobs'
    if params[:department].present?
    @jobs = []
    Job.searchdescription(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page]).each { |job|
      if job.user.department == params[:department]
        @jobs.push( job )
      end
    }
    else
      @jobs = Job.searchdescription(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
    end
    @departments = Set.new
    User.all.each { |user|
      if user.department?
        if !user.jobs.empty? 
          @departments.add(user.department) 
        end
      end
      }
    @departments.to_a.sort
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  # show a particular job listing. 
  def show
    @job = Job.find(params[:id])
    @title = Job.find(params[:id]).title
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # create a new job listing, only if you are a professor.
  def new
    @job = Job.new
    @title = 'New Job'
    if User.find(remember_token[0]).usertype != 1
      redirect_to(user_profile_path(remember_token[0]))
    else
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @job }
      end
    end
  end

  # edit a job listing, but only if you are the user who created the listing
  def edit
    @job = Job.find(params[:id])
    @title = Job.find(params[:id]).title
    if remember_token[0] != @job.user_id
      redirect_to(user_profile_path(remember_token[0]))
    end
  end

  # create a new job listing, but only if you are a professor
  def create
    @job = Job.new(params[:job])
    @job.user_id = remember_token[0]
    if User.find(remember_token[0]).usertype != 1
      redirect_to(user_profile_path(remember_token[0]))
    else
    respond_to do |format|
      if @job.save
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end
end

  # update a job listing, but only if you created the original listing. 
  # edit calls update
  def update
    @job = Job.find(params[:id])
    if remember_token[0] != @job.user_id
      redirect_to(user_profile_path(remember_token[0]))
    end
    @title = 'Edit Job'
    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to(@job, :notice => 'Job was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # delete job listing, but only if you are the one who originally created it.
  def destroy
    @job = Job.find(params[:id])
    if remember_token[0] != @job.user_id
      redirect_to(user_profile_path(remember_token[0]))
    else
      @job.destroy
      @title = 'Delete Job'
      respond_to do |format|
        format.html { redirect_to(user_profile_path(remember_token[0])) }
        format.xml  { head :ok }
      end
    end
  end

  private
    #deny user access to page, unless logged in
    def authenticate
      deny_access unless signed_in?
    end
    
    #sorting
    def sort_column
      Job.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end
    def sort_direction
      %W[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div style='float: left; width: 400px;'>
  <div class="field">
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </div> 
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  </div>
  <div style='float: right; width: 400px;'>
  <div class="field">
    <%= f.label :funding %><br />
    <%= f.text_field :funding %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  </div>
  <div style="clear: both">
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_jobs.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class ="pretty">
  <tr id = "theader">
    <th><%= sortable "position" %></th>
    <th>Description</th>
    <th><%= sortable "user.lastname", "Professor" %></th>
    <th><%= sortable "location" %></th>
    <th><%= sortable "duration" %></th>
    <th><%= sortable "user.department", "Department" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.position %></td>
    <td><%= job.description %></td>
    <td><%= job.user.firstname %> <%=job.user.lastname%></td>
    <td><%= job.location %></td>
    <td><%= job.duration %></td>
    <td><%= job.user.department %></td>
    <td><%= link_to 'Show', job %></td>   
    <% if User.find(remember_token[0]).usertype == 1%>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Delete', job, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %> 
   </tr> 
<% end %>
</table>

<%= will_paginate @jobs %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<%= form_tag({:controller => "jobs", :action => "index"}, :method => "get") do %>
  <%= label_tag(:department, "Department")%>
  <%= select_tag "department", options_for_select(@departments) %>
  <%= submit_tag("Filter") %>
  <% end %>

<%= form_tag jobs_path, :method => 'get', :id => "jobs_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Description", :name => nil %>
  </p>
<div id="jobs"><%= render 'jobs' %></div>
<% end %>


 

app/views/jobs/index.js.erb
$('#jobs').html('<%= escape_javascript(render("jobs")) %>');
alert("hello");

app/views/jobs/new.html.erb
<h1>New Job</h1>
<div style="float: left">
<%= render 'form' %>
</div>

app/views/jobs/show.html.erb
<div id='left'>
<h1> Job Description </h1>
<div id='leftin'>
<p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Funding:</b>
  <%= @job.funding %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>

<p>
  <b>Duration:</b>
  <%= @job.duration %>
</p>

<p>
  <b>Position:</b>
  <%= @job.position %>
</p>

<p>
  <b>Location:</b>
  <%= @job.location %>
</p>
  <% if remember_token[0] == @job.user.id %>
    <div id="edit">
      <%= link_to 'Edit', edit_job_path(@job) %>
    </div>
  <%elsif User.find(remember_token[0]).usertype == 0%>
  <div id='edit'>
    <%= button_to 'Apply', new_submission_path + "/" + @job.id.to_s %>
  </div>
  <%end%>
</div>
</div>

<% if User.find(remember_token[0]).usertype == 1%>
  <div id='right'> 
  <h1>Applications To This Job</h1>
  <div id='rightin'>
  <table>
    <tr>
      <th>Applicant Name</th>
      <th></th>
    </tr>

  <% @job.submissions.each do |submission| %>
    <tr>
      <td><%= submission.user.firstname %> <%= submission.user.lastname %></td>
      <td><%= link_to 'Show', submission %></td>
    </tr>
  <% end %>
  </table>
  </div>
  </div>
<% end %>