config/routes.rb
Research4::Application.routes.draw do
  resources :favorites

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :submissions
    match '/submissions/new/:jobid', :to => 'submissions#new', :as => "submission_new"
  resources :jobs
  resources :users
    match '/profile/:id', :to => 'users#profile', :as => "user_profile"
    match '/users/:id/changepassword', :to => 'users#changepassword', :as => "changepassword_user"
  resources :sessions, :only => [:new, :create, :destroy]
    match '/signup/student',  :to => 'users#new0', :as => 'signup0'
    match '/signup/professor', :to => 'users#new1', :as => 'signup1'
    match '/signin/student',  :to => 'sessions#new0', :as => 'signin0'
    match '/signin/faculty',  :to => 'sessions#new1', :as => 'signin1'
    match '/signout', :to => 'sessions#destroy', :as => 'signout'
    match '/session/retry/:usertype', :to => 'sessions#create'
    match '/help', :to => 'sessions#new'
    match '/welcome/:id/:code', :to => 'users#welcome'
  root :to => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Users can file many submissions and post many jobs (depending on status)
  has_many :submissions
  has_many :jobs
  has_many :favorites
  
  named_scope :with_department, lambda {|department| where(:department => department) }
  named_scope :with_type, lambda {|type| where(:usertype => type)}
  named_scope :with_concentration, lambda {|concentration| where(:concentration => concentration) }

  # arrays for drop-down form lists
  YEARS = [2011, 2012, 2013, 2014]
  CONCENTRATIONS =  ["African and African American Studies", "Anthropology", "Applied Mathematics", "Astrophysics",
                    "Biomedical Engineering", "Chemical and Physical Biology", "Chemistry", "Chemistry and Physics",
                    "Classics", "Computer Science", "Earth and Planetary Science", "East Asian Studies", "Economics",
                    "Engineering Sciences", "English", "Environmental Science and Public Policy",
                    "Folklore and Mythology", "Germanic Languages and Literatures", "Government", "History",
                    "History and Literature", "History of Art and Architecture", "History of Science",
                    "Human Developmental and Regenerative Biology", "Human Evolutionary Biology", "Linguistics",
                    "Literature", "Mathematics", "Molecular and Cellular Biology", "Music",
                    "Near Eastern Languages and Civilizations", "Neurobiology", "Organismic and Evolutionary Biology",
                    "Philosophy", "Physics", "Psychology", "Comparative Study of Religion",
                    "Romance Languages and Literatures", "Sanskrit and Indian Studies",
                    "Slavic Languages and Literatures", "Social Studies", "Sociology", "Special Concentration",
                    "Statistics", "Undeclared", "Visual and Environmental Studies",
                    "Studies of Women, Gender, and Sexuality"]
  SECONDARYS = ["African and African American Studies", "Anthropology", "Archaeology", "Astrophysics",
               "Celtic Languages and Literatures", "Chemistry", "Classics", "Computer Science", "Dramatic Arts",
               "Earth and Planetary Science", "East Asian Studies", "Economics", "English",
               "Environmental Science and Public Policy", "Ethnic Studies", "Folklore and Mythology",
               "Germanic and Scandinavian Studies", "Global Health and Health Policy", "Government", "History",
               "History and Literature", "History of Art and Architecture", "History of Science",
               "Human Evolutionary Biology", "Linguistics", "Literature", "Mathematical Sciences", "Medieval Studies",
               "Microbial Sciences", "Mind/Brain/Behavior", "Molecular and Cellular Biology", "Music",
               "Near Eastern Languages and Civilizations", "Neurobiology", "Organismic and Evolutionary Biology",
               "Philosophy", "Physics", "Psychology", "Comparative Study of Religion",
               "Romance Languages and Literatures", "Russia, Eastern Europe, and Central Asia",
               "Sanskrit and Indian Studies", "Slavic Languages and Literatures", "Sociology", "Statistics",
               "Visual and Environmental Studies", "Studies of Women, Gender, and Sexuality"]
  DEPARTMENTS = ["African and African American Studies", "Anthropology", "Astronomy", "Celtic Languages and Literatures",
                "Chemistry and Chemical Biology", "The Classics", "Comparative Literature",
                "Earth and Planetary Sciences", "East Asian Languages and Civilizations", "Economics", "English",
                "Germanic Languages and Literatures", "Government", "History", "History of Art and Architecture",
                "History of Science", "Human Evolutionary Biology", "Linguistics", "Mathematics",
                "Molecular and Cellular Biology", "Music", "Near Eastern Languages and Civilizations",
                "Organismic and Evolutionary Biology", "Philosophy", "Physics", "Psychology",
                "Romance Languages and Literatures", "Sanskrit and Indian Studies",
                "Slavic Languages and Literatures", "Sociology", "Statistics", "Stem Cell and Regenerative Biology",
                "Visual and Environmental Studies"]

  # change display names of certain variables to "humanized" versions
  HUMANIZED_ATTRIBUTES = { :email => "E-mail address", :firstname => "First name", :lastname => "Last name",
                           :phone => "Phone number", :gpa => "GPA", :old_password => "Old Password"}
  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  # make password a "virtual attribute", also make attributes accessible
  attr_accessor :password, :old_password
  attr_accessible :firstname, :lastname, :email, :phone, :year, :concentration, :secondary, :gpa, :resume, :location, :interests, :title, :department, :password, :password_confirmation, :usertype, :verified

  # search method for resume
  def self.searchresume(search)
    if search
      where('resume LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  # search method for interests
  def self.searchinterests(search)
    if search
      where('interests LIKE ?', "%#{search}%")
    else
      scoped
    end
  end


    # Regular expression for email format verification
    email_regex = /\A[\w+\-.]+@(fas.harvard.edu|college.harvard.edu)/

    # Validations for attributes
    validates :firstname, :presence => true,
                          :length   => { :maximum => 50 }
    validates :lastname, :presence   => true,
                         :length     => { :maximum => 50 },
                         :uniqueness => { :scope => :firstname }
    validates :email, :presence   => true,
                      :uniqueness => { :case_sensitive => false },
                      :length     => { :maximum => 50 }
    validates_format_of :email, :allow_blank => true, :with => email_regex
    validates_numericality_of :phone, :allow_blank => true
    validates :phone, :length       => { :maximum => 15 }

     def password
      if !self.new_record?  
        if @password.nil?
          '123456'
        else
          @password
        end
      else
        @password
      end
    end

    # Student? method to determine if user is a student
    def student?
      :usertype == 0
    end

    # Student-only validations
    validates_numericality_of :gpa, :allow_blank => true
    validates_length_of :resume, :maximum => 3000
    validates_presence_of :concentration, :if => :student?

    # Professor? method to determine if user is a professor
    def professor?
      :usertype == 1
    end

    # Professor-only validations
    validates_presence_of :title, :if => :professor?
    validates :title, :length => { :maximum => 300 }
    validates :location, :length => { :maximum => 300 }
    validates_presence_of :department, :if => :professor?
    validates :department, :length => { :maximum => 300 }
    validates :interests, :length => { :maximum => 3000}

    # Confirmation validations for password
    validates :password, :presence     => true,
                         :confirmation => true
    validates_length_of :password, :allow_blank => true, :within => 6..40

    before_save :encrypt_password
      # Return true if the user's password matches the submitted password (uses stored salt).
      def has_password?(submitted_password)
        encrypted == encrypt(submitted_password)
      end

      # Return nil if email not found, return user only if password is right, else auto-return nil
      def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil  if user.nil?
        return user if user.has_password?(submitted_password)
      end

      # Return user if user/salt matches the cookie, else returns nil
      def self.authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
      end

      private
        # Create salt if new user (via call to Active Record's method),
        # then encrypt password accordingly
        def encrypt_password
          self.salt = make_salt if new_record?
          self.encrypted = encrypt(password)
        end

        # Encrypt password with salt and inputted password
        def encrypt(string)
          secure_hash("#{salt}--#{string}")
        end

        # Creation of salt, unique string for user dependent on time of account creation and password
        def make_salt
          secure_hash("#{Time.now.utc}--#{password}")
        end

        # Use SHA2 hash function
        def secure_hash(string)
          Digest::SHA2.hexdigest(string)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Note: Students have usertype = 0 and Professors have usertype = 1
  # Make sure user is logged in
  before_filter :authenticate, :only => [:index, :show, :edit, :update, :destroy, :profile]
  before_filter :correct_user, :only => [:update, :destroy, :edit]

  helper_method :sort_column, :sort_direction	
  
  # show all users
  def index
    if User.find(remember_token[0]).usertype == 0
      @title = 'Faculty'
      if params[:department].present?
        @users = User.with_department(params[:department]).searchinterests(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
      else
        @users = User.with_type(1).searchinterests(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
      end
    elsif User.find(remember_token[0]).usertype == 1
      @title = 'Students'
      if params[:concentration].present?
        @users = User.with_concentration(params[:concentration]).searchresume(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
      else
	@users = User.with_type(0).searchresume(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
      end
    else
      @users = User.all.searchresume(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
      @title = 'All Users'
    end
    
    @departments = Set.new
    User.all.each { |user|
      if user.department?
        @departments.add(user.department)
      end
      }
    @departments = @departments.to_a.sort

    @concentrations = Set.new
    User.all.each { |user|
      if user.concentration?
        @concentrations.add(user.concentration)
      end
      }
    @concentrations = @concentrations.to_a.sort

    # render pages	
    respond_to do |format|
      format.js
      format.html
      format.xml  { render :xml => @users }
    end 
  end

  # show a specific user
  def show
  if params[:id] == remember_token[0]
    redirect_to(user_profile_path(remember_token[0]))
  else  
    @user = User.find(params[:id])
    @title = @user.firstname
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  end

  # create a new student
  def new0
    @user = User.new
    @user.verified = 0
    @user.usertype = 0
    @title = "Sign Up"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # create a new professor
  def new1
    @user = User.new
    @user.usertype = 1
    @user.verified = 0
    @title = "Sign Up"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end


  # edit profile
  def edit
    if current_user?(@user)
      @title = "Edit Profile"
    else
      redirect_to(edit_user_path(remember_token[0]))
    end
  end

  # create new user dependent on status as student or professor
  def create
    @user = User.new(params[:user])
    @user.code = 100000000000000+ rand(899999999999999)
    @user.verified = 0
    respond_to do |format|
      if @user.save
        Notifications.signup(@user).deliver
        if @user.usertype == 0
          format.html { redirect_to(signin0_path, :notice => "Mail sent.  Check your email to confirm your registration.")}
        else @user.usertype == 1
          format.html { redirect_to(signin1_path, :notice => "Mail sent.  Check your email to confirm your registration.")}
        end
      else 
        @title = "Sign Up"
        if @user.usertype == 0
          format.html { render :action => "new0" }
        else
          format.html { render :action => "new1" }
        end
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # welcome user to new profile
  def welcome
    @user = User.find(params[:id])
    respond_to do |format|
        if @user.code.to_s == params[:code] 
          @user.verified = 1
          @user.save!
          sign_in @user
          flash[:success] = "Welcome to Harvard Research!"
          format.html { redirect_to(user_profile_path(@user.id.to_s), :notice => 'User was successfully created.' ) }
          format.xml { render :xml => @user, :status => :created, :location => @student }
        else
          if @user.usertype == 0
            format.html { redirect_to(signin0_path, :notice => 'Registration failed.  Please wait 24 h to re-register.')}
          else
            format.html { redirect_to(signin1_path, :notice => 'Registration failed.  Please wait 24 h to re-register.')}
          end
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
    end
  end
  
  def changepassword
    if params[:id] == remember_token[0].to_s
      @title = "Change Password"
      @user = User.find(params[:id])
    else
      redirect_to(changepassword_user_path(remember_token[0]))
    end  
  end
  
  # help edit profile
  def update
    @user = User.find(params[:id])
    respond_to do |format|
    if @user.has_password?(params[:user][:old_password]) 
      if @user.update_attributes(params[:user])
        format.html { redirect_to(user_profile_path(params[:id]), :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    else
      format.html { redirect_to(edit_user_path(params[:id]), :notice => 'Incorrect Password. Update failed.') }
    end
  end
end

  # delete a user
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  #user profile page
  def profile
    @user = User.find(params[:id])
    @title = @user.firstname
    if @user.id == remember_token[0]  
      if @user.usertype == 1
        @jobs = @user.jobs
        respond_to do |format|
          format.html # profile.html.erb
          format.xml  { render :xml => @jobs }
        end
      else
        @submissions = @user.submissions
        respond_to do |format|
          format.html # profile.html.erb
          format.xml { render :xml => @submissions }
        end
      end
    else
      redirect_to(user_profile_path(remember_token[0]))
    end
  end

  private
    #deny user access to page, unless logged in
    def authenticate
      deny_access unless signed_in?
    end

    #deny user access to page, unless he has permissions
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    #sorting
    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "lastname"
    end
    
    def sort_direction
      %W[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/users/_form0.html.erb
<div id="line"></div>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="left">
  <div class="field">
    <%= f.hidden_field :usertype %>
  </div>
  <div class="field">
    <%= f.label :firstname, "First Name" %><br />
    <%= f.text_field :firstname, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :lastname, "Last Name" %><br />
    <%= f.text_field :lastname, :size => 30 %>
  </div>
  <div class ="field">
    <%= f.label :old_password, "Old Password" %><br /> 
    <%= f.password_field :old_password, :size => 30 %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :size => 30 %>
  </div>
  </div>
  <div id="right">
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br />
    <%= f.text_field :phone, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.select :year, User::YEARS, :prompt => "Select a year", :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :concentration %><br />
    <%= f.select :concentration, User::CONCENTRATIONS, :prompt => "Select your primary concentration", :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :secondary %><br />
    <%= f.select :secondary, User::SECONDARYS, :prompt => "Select a secondary" , :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :gpa , "GPA" %><br />
    <%= f.text_field :gpa, :size => 30 %>
  </div>
  </div>
  <div id="bottom">
  <div class="field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br />
    <%= f.check_box :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/users/_form1.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :usertype %>
  </div>
  <div id="left">
  <div class="field">
    <%= f.label :firstname, "First Name" %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, "Last Name" %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  </div>
  <div id="right">
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.select :department, User::DEPARTMENTS, :prompt => "Select primary affiliation" %>
  </div>
  </div>
  <div id="bottom">
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_area :interests %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br />
    <%= f.check_box :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/users/_form2.html.erb
<div id="line"></div>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="left">
  <div class="field">
    <%= f.hidden_field :usertype %>
  </div>
  <div class="field">
    <%= f.label :firstname, "First Name" %><br />
    <%= f.text_field :firstname, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :lastname, "Last Name" %><br />
    <%= f.text_field :lastname, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :old_password, "Old Password" %><br />
    <%= f.password_field :old_password, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :size => 30, :value => '' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :size => 30 %>
  </div>
  </div>
  <div id="right">
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br />
    <%= f.text_field :phone, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.select :year, User::YEARS, :prompt => "Select a year", :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :concentration %><br />
    <%= f.select :concentration, User::CONCENTRATIONS, :prompt => "Select your primary concentration", :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :secondary %><br />
    <%= f.select :secondary, User::SECONDARYS, :prompt => "Select a secondary" , :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :gpa , "GPA" %><br />
    <%= f.text_field :gpa, :size => 30 %>
  </div>
  </div>
  <div id="bottom">
  <div class="field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br />
    <%= f.check_box :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/users/_form6.html.erb
<%= form_for(@user) do |f|%>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :old_password, "Old Password" %><br />
    <%= f.password_field :old_password, :size => 30 %>
  </div>
  <div class="field">
    <label> New Password </label><br />
    <%= f.password_field :password, :value => '' %>
  </div>
  <div class="field">
    <label> Confirm New Password </label><br />
    <%= f.password_field :password_confirmation %>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/users/changepassword.html.erb
<h1> Change Password </h1>

<%=render 'form6' %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>


<% if User.find(remember_token[0]).usertype == 0 %>
<%= render 'form5' %>
<% else %>
<%= render 'form4' %>
<% end %>

app/views/users/index.html.erb
<% if User.find(remember_token[0]).usertype != 0 %>
  <h1>Students</h1>
<% elsif User.find(remember_token[0]).usertype != 1%>
  <h1>Faculty</h1>
<%end%>

<% if User.find(remember_token[0]).usertype == 0 %>
    <%= form_tag({:controller => "users", :action => "index"}, :method => "get") do %>
      <%= label_tag(:department, "Department")%>
      <%= select_tag "department", options_for_select(@departments) %>
      <%= submit_tag("Filter") %>
  <% end %>
<% elsif User.find(remember_token[0]).usertype == 1 %>
    <%= form_tag({:controller => "users", :action => "index"}, :method => "get") do %>
      <%= label_tag(:concentration, "Concentration")%>
      <%= select_tag "concentration", options_for_select(@concentrations) %>
      <%= submit_tag("Filter") %>
    <% end %>
<% end %>

<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <% if User.find(remember_token[0]).usertype == 0 %>	
      <%= submit_tag "Search Interests", :name => nil %>
    <% else %>
      <%= submit_tag "Search Resumes", :name => nil %>	
    <% end %>  	
  </p>
  <div id="users"><%= render 'users' %></div>
<% end %>

app/views/users/index.js.erb
$('#users').html('<%= escape_javascript(render("users")) %>');
$('.pretty1 tr:not(.odd)').hide();
$('.pretty1 tr:first-child').show();
$('.pretty1 tr.odd').click(function(){
  $(this).next("tr").toggle();
});

app/views/users/new0.html.erb
<h1>New User</h1>

<%= render 'form0' %>



app/views/users/profile.html.erb
<div id='left'>
  <h1> Your Profile </h1>
  <div id='leftin'>
    <p>
      <b>First Name:</b>
      <%= @user.firstname %>
    </p>
    <p>
      <b>Last Name:</b>
      <%= @user.lastname %>
    </p>
    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>
    <p>
      <b>Phone Number:</b>
      <%= @user.phone %>
    </p>

    <% if User.find(remember_token[0]).usertype != 1 %>
        <p>
          <b>Year:</b>
          <%= @user.year %>
        </p>
        <p>
          <b>Concentration:</b>
          <%= @user.concentration %>
        </p>
        <p>
          <b>Secondary:</b>
          <%= @user.secondary %>
        </p>
        <p>
          <b>GPA:</b>
          <%= @user.gpa %>
        </p>
        <p>
          <b>Resume:</b>
          <%= @user.resume %>
        </p>
    <% elsif User.find(remember_token[0]).usertype != 0 %>
        <p>
          <b>Interests:</b>
          <%= @user.interests %>
        </p>
        <p>
          <b>Title:</b>
          <%= @user.title %>
        </p>
        <p>
          <b>Location:</b>
          <%= @user.location %>
        </p>
        <p>
          <b>Department:</b>
          <%= @user.department %>
        </p>
    <% end %>
    <% if remember_token[0] == @user.id %>
      <div id='edit'>
        <%= link_to 'Edit', edit_user_path(@user) %>
      </div>
   <%end%>
  </div>
</div>
<div id='right'>
  <% if @user.usertype == 0 %>
    <h1>Your Applications</h1>
    <div id='rightin'>
    <table>
      <tr>
        <th>Job Title</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @submissions.each do |submission| %>
      <tr>
        <% if !submission.job.nil? %>
        <td><%= submission.job.title %></td>
        <% else %>
        <td>(job deleted)
        <% end %>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Delete', submission, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
  <% elsif @user.usertype == 1 %>
    <h1>Your Jobs</h1>
    <div id='rightin'>
    <table>
      <tr>
        <th>Title</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Delete', job, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
<% else %>
    <%= link_to 'Job Listings', jobs_path %> |
    <%= link_to 'Professor List', users_path %> |
    <%= link_to 'Submissions List', submissions_path %> |
    <%= link_to 'Back', user_profile_path(remember_token[0]) %>
<% end %> 