config/routes.rb
Research4::Application.routes.draw do
  resources :favorites

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :submissions
    match '/submissions/new/:jobid', :to => 'submissions#new', :as => "submission_new"
  resources :jobs
  resources :users
    match '/profile/:id', :to => 'users#profile', :as => "user_profile"
    match '/users/:id/changepassword', :to => 'users#changepassword', :as => "changepassword_user"
  resources :sessions, :only => [:new, :create, :destroy]
    match '/signup/student',  :to => 'users#new0', :as => 'signup0'
    match '/signup/professor', :to => 'users#new1', :as => 'signup1'
    match '/signin/student',  :to => 'sessions#new0', :as => 'signin0'
    match '/signin/faculty',  :to => 'sessions#new1', :as => 'signin1'
    match '/signout', :to => 'sessions#destroy', :as => 'signout'
    match '/session/retry/:usertype', :to => 'sessions#create'
    match '/help', :to => 'sessions#new'
    match '/welcome/:id/:code', :to => 'users#welcome'
  root :to => 'sessions#new'

end

app/views/layouts/_footer.html.erb
 <footer>
 </footer>

app/views/layouts/_header.html.erb
<header>
  <%if signed_in?%>
    <div id="logo2"> 
      <%= link_to logo, user_profile_path(remember_token[0].to_s) %>
    </div>
    <div id='linkbar'>
      <%= link_to "Profile", user_profile_path(remember_token[0].to_s) %> |
      <%= link_to "Change Password", changepassword_user_path(remember_token[0].to_s) %> |
      <% if User.find(remember_token[0]).usertype == 0 %>
        <%= link_to 'Jobs', jobs_path %> | 
        <%= link_to 'Faculty', users_path %> |
      <%else%>
        <%= link_to 'New Job', new_job_path %> |
        <%= link_to 'Students', users_path %> |
      <%end%>
      <%= link_to 'Sign Out', signout_path, :method => :delete %>
    </div>
  <%else%>
    <div id="logo">
      <%= link_to root_path do %>
        <img src='/images/largelogo.png'>
      <% end %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HarvardResearch | <%= @title %></title>

   <!--[if lt IE 9]>
   <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
   <![endif]-->
   <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin:bold', :media => 'screen' %>
   <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
   <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
   <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag 'jquery', 'rails', 'application' %>
  <%= csrf_meta_tag %>
  <% if !signed_in? %>
    <style>
      div#wrapper0 {
        background-image:url('/images/MortarBoard.jpg');
        height: 400px;
        margin-left: auto;
        margin-right: auto;
      }
    </style>
    <% else %>
    <script type="text/javascript">
      $(document).ready(function(){
          $(".pretty1 tr:not(.odd)").hide();
          $(".pretty1 tr:first-child").show();
        
          $(".pretty1 tr.odd").click(function(){
              $(this).next("tr").toggle();
          });
      });
    </script>
    <% end %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20932570-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
  <div class="container"> 
    <div id="wrapper">
      <%= render 'layouts/header' %>
    <% if !signed_in? %>
      <div id="wrapper0">
    <% else %>
      <div id="wrapper1">
    <% end %>
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <% if signed_in? %>
      <div id='footer'>
      </div>
    <% end %>
  </div>
</body>


</html>